spring:
  application:
    name: marquee-api
  main:
    banner-mode: "off"

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    name: Marquee API
    version: 0.1.0
